version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - opensearch-config:/usr/share/opensearch/config
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
    networks:
      - opensearch-net
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
     # - opensearch-config/
    ports:
      - "5044:5044"
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node1
volumes:
  opensearch-data1:
  opensearch-config:

networks:
  opensearch-net:
   ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
